package probotica.modelo.entidad;
// Generated 07/06/2015 09:56:10 PM by Hibernate Tools 4.3.1



/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private String iddocumento;
     private String nomcomprobante;

    public Comprobante() {
    }

	
    public Comprobante(String iddocumento) {
        this.iddocumento = iddocumento;
    }
    public Comprobante(String iddocumento, String nomcomprobante) {
       this.iddocumento = iddocumento;
       this.nomcomprobante = nomcomprobante;
    }
   
    public String getIddocumento() {
        return this.iddocumento;
    }
    
    public void setIddocumento(String iddocumento) {
        this.iddocumento = iddocumento;
    }
    public String getNomcomprobante() {
        return this.nomcomprobante;
    }
    
    public void setNomcomprobante(String nomcomprobante) {
        this.nomcomprobante = nomcomprobante;
    }




}


