package probotica.modelo.entidad;
// Generated 26/05/2015 10:45:33 AM by Hibernate Tools 4.3.1



/**
 * Distribuidor generated by hbm2java
 */
public class Distribuidor  implements java.io.Serializable {


     private String iddistribuidor;
     private String nombredistribuidor;
     private String direccion;
     private String telefonoCelular;
     private String correo;
     private String estado;
     private String ruc;

    public Distribuidor() {
        this.setIddistribuidor("");
    }

	
    public Distribuidor(String iddistribuidor) {
        this.iddistribuidor = iddistribuidor;
    }
    public Distribuidor(String iddistribuidor, String nombredistribuidor, String direccion, String telefonoCelular, String correo, String estado, String ruc) {
       this.iddistribuidor = iddistribuidor;
       this.nombredistribuidor = nombredistribuidor;
       this.direccion = direccion;
       this.telefonoCelular = telefonoCelular;
       this.correo = correo;
       this.estado = estado;
       this.ruc = ruc;
    }
   
    public String getIddistribuidor() {
        return this.iddistribuidor;
    }
    
    public void setIddistribuidor(String iddistribuidor) {
        this.iddistribuidor = iddistribuidor;
    }
    public String getNombredistribuidor() {
        return this.nombredistribuidor;
    }
    
    public void setNombredistribuidor(String nombredistribuidor) {
        this.nombredistribuidor = nombredistribuidor;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }




}


