package probotica.modelo.entidad;
// Generated 26/05/2015 10:45:33 AM by Hibernate Tools 4.3.1



/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private String idlaboratorio;
     private String nombrelaboratorio;

    public Laboratorio() {
    }

	
    public Laboratorio(String idlaboratorio) {
        this.idlaboratorio = idlaboratorio;
    }
    public Laboratorio(String idlaboratorio, String nombrelaboratorio) {
       this.idlaboratorio = idlaboratorio;
       this.nombrelaboratorio = nombrelaboratorio;
    }
   
    public String getIdlaboratorio() {
        return this.idlaboratorio;
    }
    
    public void setIdlaboratorio(String idlaboratorio) {
        this.idlaboratorio = idlaboratorio;
    }
    public String getNombrelaboratorio() {
        return this.nombrelaboratorio;
    }
    
    public void setNombrelaboratorio(String nombrelaboratorio) {
        this.nombrelaboratorio = nombrelaboratorio;
    }




}


