package probotica.modelo.entidad;
// Generated 26/05/2015 10:45:33 AM by Hibernate Tools 4.3.1



/**
 * TipoIngreso generated by hbm2java
 */
public class TipoIngreso  implements java.io.Serializable {


     private String idtipoingreso;
     private String nomtipoingreso;

    public TipoIngreso() {
    }

	
    public TipoIngreso(String idtipoingreso) {
        this.idtipoingreso = idtipoingreso;
    }
    public TipoIngreso(String idtipoingreso, String nomtipoingreso) {
       this.idtipoingreso = idtipoingreso;
       this.nomtipoingreso = nomtipoingreso;
    }
   
    public String getIdtipoingreso() {
        return this.idtipoingreso;
    }
    
    public void setIdtipoingreso(String idtipoingreso) {
        this.idtipoingreso = idtipoingreso;
    }
    public String getNomtipoingreso() {
        return this.nomtipoingreso;
    }
    
    public void setNomtipoingreso(String nomtipoingreso) {
        this.nomtipoingreso = nomtipoingreso;
    }




}


