package probotica.modelo.entidad;
// Generated 07/06/2015 09:56:10 PM by Hibernate Tools 4.3.1



/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private String idUnidadmedida;
     private String unidadmedida;

    public UnidadMedida() {
    }

	
    public UnidadMedida(String idUnidadmedida) {
        this.idUnidadmedida = idUnidadmedida;
    }
    public UnidadMedida(String idUnidadmedida, String unidadmedida) {
       this.idUnidadmedida = idUnidadmedida;
       this.unidadmedida = unidadmedida;
    }
   
    public String getIdUnidadmedida() {
        return this.idUnidadmedida;
    }
    
    public void setIdUnidadmedida(String idUnidadmedida) {
        this.idUnidadmedida = idUnidadmedida;
    }
    public String getUnidadmedida() {
        return this.unidadmedida;
    }
    
    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }




}


